Yes, task_4 has been created now. 
